### ISSUE TITLE
small encapsulation problem

### ISSUE THREAD

**Issue by MichelleZ** [xuperchain/xuperunion#104]
**Brief of the issue**
Describe here
Enhance encapsulation

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by yucaowang** [comment]
close as fixed by #105
