### ISSUE TITLE
deploy contract failed (getting started)

### ISSUE THREAD

**Issue by doreamon95** [xuperchain/xuperunion#115]
**#Q** go Language：deployment contract failed
Deployment code: The compiled contract is placed in the data/counter/counter directory
` ./xchain-cli wasm deploy --account XC1111111111111111@xuper --cname counter -H localhost:37101 -a '{"creator":"xchain"}' data/counter/counter --runtime go`
**error:**
PreExe contract response : rpc error: code = Unknown desc = get account XC1111111111111111@xuper error: Key not found

Firstly, I executed the Create Account command.`./xchain-cli account new --account 1111111111111111` and returned `contract response and the gas you consume is : 1000 , you need add free` . Then I checked the account under `data/accounts`, no 1111111111111111, only the account alice and bob. 
and then I executed the command : `/xchain-cli acl query --account XC1111111111111111@xuper` and returned `null  /   unconfirmed` .  So it means ......

**Comment by qizheng09** [comment]
Have you created an account?

**Comment by doreamon95** [comment]
> Have you created an account?

Yes ，a contract account has been created and the code is : 

> ./xchain-cli account new --account 1111111111111111

Also created alice and bob
