### ISSUE TITLE
The consensus contract return nil though it run failed

### ISSUE THREAD

**Issue by qizheng09** [xuperchain/xuperunion#116]
**Brief of your idea**
The consensus contract return `nil` though it run failed. This is inconvenient for users.

**What could be better if XuperChain using your idea**
Return `error` information so that `core` can marked it.

**Comment by doreamon95** [comment]
Do you know what the reason is?
PreExe contract response : rpc error: code = Unknown desc = get account `XC1111111111111111@xuper` error: Key not found

**Comment by ToWorld** [comment]
Have you created the account of XC1111111111111111@xuper already?

**Comment by doreamon95** [comment]
> XC1111111111111111@xuper
yes,also charged an amount

> ./xchain-cli account balance XC1111111111111111@xuper

return 100100

**Comment by doreamon95** [comment]
> Have you created the account of XC1111111111111111@xuper already?

yes, also charged an amount

>  ./xchain-cli account balance XC1111111111111111@xuper

return 100100

**Comment by ToWorld** [comment]
> > Have you created the account of XC1111111111111111@xuper already?
> 
> yes, also charged an amount
> 
> > ./xchain-cli account balance XC1111111111111111@xuper
> 
> return 100100

The error information of "rpc error: code = Unknown desc = get account XC1111111111111111@xuper error: Key not found" means that you haven't create the contract account of XC1111111111111111@xuper , and the only way to check if you have created the account of XC1111111111111111@xuper is to query the acl information of XC1111111111111111@xuper, such as the command of `./xchain-cli acl query --account XC1111111111111111@xuper` instead of using the command of `./xchain-cli account balance XC1111111111111111@xuper`.

**Comment by doreamon95** [comment]
> > > Have you created the account of XC1111111111111111@xuper already?
> > 
> > 
> > yes, also charged an amount
> > > ./xchain-cli account balance XC1111111111111111@xuper
> > 
> > 
> > return 100100
> 
> The error information of "rpc error: code = Unknown desc = get account XC1111111111111111@xuper error: Key not found" means that you haven't created the contract account of XC1111111111111111@xuper , and the efficient way to check if you have created the account of XC1111111111111111@xuper is to query the acl information of XC1111111111111111@xuper, such as the command of `./xchain-cli acl query --account XC1111111111111111@xuper` instead of using the command of `./xchain-cli account balance XC1111111111111111@xuper`.
> It is just like taking a command of `./xchain-cli transfer --to bob --amount 100` doesn't mean you have created the address of bob though you can get the balance of bob using the command of `./xchain-cli account balance bob`. Right?

Yes,and I execute the query command

> ./xchain-cli acl query --account XC1111111111111111@xuper
return : 

> null
> unconfirmed
But I execute the command

> /xchain-cli account balance XC1111111111111111@xuper
return: 100100
**So does it mean that the account creation failed?**

**Comment by ToWorld** [comment]
No,I guess that you haven't created the account with the command of `./xchain-cli account new --account 1111111111111111`

**Comment by doreamon95** [comment]
> No,I guess that you haven't created the account with the command of `./xchain-cli account new --account 1111111111111111`
Firstly, I executed the Create Account command.`./xchain-cli account new --account 1111111111111111` and returned `contract response and the gas you consume is : 1000 , you need add free` . Then I checked the account under `data/accounts`, no 1111111111111111, only the account alice and bob. 
and then I executed the command : `/xchain-cli acl query --account XC1111111111111111@xuper` and returned `null  /   unconfirmed` .  So it means ......
