### ISSUE TITLE
Parameters are not used 

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#134]
**Brief of the issue**
flags Parameters are not used ,May I delete it?

**Repo steps**
 https://github.com/xuperchain/xuperunion/blob/e35a2156c94154232fa3bf7e78c2105675575266/cmd/xchain/xchain.go#L110

**Expected behaviours**
cfg.LoadConfig()

**What actually happened**
cfg.LoadConfig(flags)

**Comment by yucaowang** [comment]
Sure, please go ahead.

**Comment by Rcvisual** [comment]
> Sure, please go ahead.

OK

**Comment by yucaowang** [comment]
close as fixed by @Rcvisual .
#135
