### ISSUE TITLE
xvm: open module failed undefined symbol: sqrt

### ISSUE THREAD

**Issue by icexin** [xuperchain/xuperunion#138]
**Brief of the issue**
deploy go wasm contract failed, found `undefined symbol: sqrt` in log

**Your environment**
OS: ubuntu 18.04
GO: 1.12.6

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by yucaowang** [comment]
close as fixed #139
