### ISSUE TITLE
对椭圆曲线P256选择考虑

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#17]
**Brief of the issue**
Describe here
出于什么原因选择了go内置的椭圆曲线P256？而不是比特币secp256k1或者ed25519算法？
**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.
文件路径crypto/client/xchain/xchain_crypto_client.go 20行
// GenerateKeyBySeed 通过随机数种子来生成椭圆曲线加密所需要的公钥和私钥
func (xcc XchainCryptoClient) GenerateKeyBySeed(seed []byte) (*ecdsa.PrivateKey, error) {
	curve := elliptic.P256()
	privateKey, err := utils.GenerateKeyBySeed(curve, seed)
	return privateKey, err
}
**Expected behaviours**
Describe what you expected to happen.
出于性能还是安全性？具体考虑方向
**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by auxten** [comment]
没有明确的证据证明 P256 不安全，至少还广泛用于 SSL

**Comment by Rcvisual** [comment]
> 没有明确的证据证明 P256 不安全，至少还广泛用于 SSL

但是区块链项目很少这么用，毕竟底层加密是一个系统的核心，应该是我多虑了

**Comment by HawkJing** [comment]
首先，P-256曲线目前依然在密码学界被广泛使用。其次，这次开源的是我们的基础版本，而在xchain的代码架构下，密码学相关的模块是插件化使用的。密码学crypto模块是可以独立研发并集成进此次开源版本的。在尚未开源的版本中，通过可变签名算法，我们已经支持国密/NIST的多条椭圆曲线。同时，在ECDSA之外，也已支持多重签名、EDDSA、环签名等多种签名算法。最后，这些算法和曲线被支持混合使用，开发者可以自由选择他们认为安全的曲线和算法来保护自己的数字资产。所以，敬请期待百度xchain后续的密码学相关开源进展。

**Comment by Rcvisual** [comment]
> 首先，P-256曲线目前依然在密码学界被广泛使用。其次，这次开源的是我们的基础版本，而在xchain的代码架构下，密码学相关的模块是插件化使用的。密码学crypto模块是可以独立研发并集成进此次开源版本的。在尚未开源的版本中，通过可变签名算法，我们已经支持国密/NIST的多条椭圆曲线。同时，在ECDSA之外，也已支持多重签名、EDDSA、环签名等多种签名算法。最后，这些算法和曲线被支持混合使用，开发者可以自由选择他们认为安全的曲线和算法来保护自己的数字资产。所以，敬请期待百度xchain后续的密码学相关开源进展。

谢谢回复，希望你们可以继续可以开源下去，我在之后会仔细阅读相关源码的，他能给我很好的借鉴作用。
