### ISSUE TITLE
Creating a parallel chain causes the node to panic

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#175]
**Brief of the issue**
json file:

{
  "Module": "kernel",
  "Method": "CreateBlockChain",
  "Args": {
    "name": "condpos",
    "data": "{\"permission\": {\"CreateAccount\" : { \"rule\" : \"Null\", \"acl\": {}},\"SetAccountAcl\": { \"rule\" : \"Null\", \"acl\": {}},\"SetContractMethodAcl\": { \"rule\" : \"Null\", \"acl\": {}}}, \"maxblocksize\": \"128\", \"award_decay\": {\"height_gap\": 31536000, \"ratio\": 1}, \"version\": \"1\", \"predistribution\": [{\"quota\": \"1000000000000000\", \"address\": \"dpzuVdosQrF2kmzumhVeFQZa1aYcdgFpN\"}], \"decimals\": \"8\", \"period\": \"3000\",\"award\": \"1000000\", \"genesis_consensus\": {\"config\": {\"init_proposer\": {\"1\": [\"dpzuVdosQrF2kmzumhVeFQZa1aYcdgFpN\", \"VSML7NenZnGZgCEwtbQDKDSrPHhT5wsu6\", \"bg3KLC3YCmvLWBCNAVHGHLfk3qeWEdoD3\"]}, \"init_proposer_neturl\": {\"1\": [\"/ip4/10.26.29.40/tcp/47101/p2p/QmUqM5tGMZCuHEBcGYbxUHr2yzLdXSBGc5ziPHm68CuqzC\", \"/ip4/10.26.29.40/tcp/47101/p2p/QmZT13hEUCPD6JuwKHkdDNAvwX8p5B2cbE5HqjYCsSQAGB\", \"/ip4/10.26.29.40/tcp/47101/p2p/QmVtVvDoxQPCecwBTaRFixAweSsnKu96uVgArMeBPUsoLV\"]}, \"timestamp\": \"1561452077000000000\", \"period\": \"3000\", \"alternate_interval\": \"6000\", \"term_interval\": \"9000\", \"block_num\": \"10\", \"vote_unit_price\": \"1\", \"proposer_num\": \"3\"}, \"name\": \"tdpos\"}}"}
}

**Your environment**
xchain-cli version v3.2-7f817ef

**Repo steps**
step1
./bin/xchain-cli transfer --to condpos  --amount 200 --desc=./condpos.json -H=$host
step2
the node panic which is  requested.
![image](https://user-images.githubusercontent.com/51076943/60861166-08c73d00-a24c-11e9-9428-b910811dfcd6.png)

**Expected behaviours**
 The parallel chain can be created and start to mine.

**What actually happened**
The node panics and creates chain failure

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by qizheng09** [comment]
fixed, so closed here.
