### ISSUE TITLE
The erc721 wasm contract invoke failed.    error status:500 message

### ISSUE THREAD

**Issue by doreamon95** [xuperchain/xuperunion#176]
**Brief of the issue**
./xchain-cli wasm invoke -a '{"action":"transfer","from":"bob","to":"alice","token_id":"1"}' --method invoke -H localhost:37102 erc721test
Error message
PreExe contract response : rpc error: code = Unknown desc = contract error status:500 message:Missing key: from, logid:1562163683405800715_1_8081

**Your environment**
ubuntu16.04    64bit    8G
g++ 5.4.0
go 1.12.6

**Repo steps**
step1 
./xchain-cli wasm deploy --account XC1111111111111111@xuper --cname erc721test -H localhost:37102 -a '{"supply":"1,2,3,4,5,6","from":"bob"}' data/erc721 --runtime go --fee 6205188

step2
./xchain-cli wasm invoke -a '{"from":"bob","supply":"1,2"}' --method initialize -H localhost:37102 erc721test --fee 101800

step3  Error occurred
./xchain-cli wasm invoke -a '{"action":"transfer","from":"bob","to":"alice","token_id":"1"}' --method invoke -H localhost:37102 erc721test

PreExe contract response : rpc error: code = Unknown desc = contract error status:500 message:Missing key: from, logid:1562163683405800715_1_8081

**Expected behaviours**
Perform different transactions through invoke, and query transactions

**What actually happened**
Deploy and initialize are correct. Invoke error?

**Additional information**

**Comment by MichelleZ** [comment]
![image](https://user-images.githubusercontent.com/10205478/60863555-b2f69300-a253-11e9-86b1-cac2e9959a11.png)
![image](https://user-images.githubusercontent.com/10205478/60863564-c144af00-a253-11e9-94f5-8915f47c3485.png)
Referring to the first picture, the parameters are modified consistently.

**Comment by doreamon95** [comment]
OK, thank you
