### ISSUE TITLE
Transfer needs fee or it will fail.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#180]
**Brief of the issue**
Transfer without fee will make a mistake when configuring  reserved contracts.But that's not the case.
**Your environment**
xchain-cli version v3.2-7f817ef

**Repo steps**
step1 
./bin/xchain-cli transfer --to=XC1562641423020263@xuper --amount=5000000
The response is :
Failed to post tx: logid:"1562661833014935008_2_1847" error:RWSET_INVALID_ERROR
step2
./bin/xchain-cli transfer --to=XC1562641423020263@xuper --amount=5000000 --fee
Successful transfer in this way which need fee.

**Expected behaviours**
Successful transfers in this way do not require fee.

**What actually happened**
Transfer without fee will fail.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
It is same as the issue #183

**Comment by ToWorld** [comment]
Closing this.
