### ISSUE TITLE
TDPOS是什么？

### ISSUE THREAD

**Issue by vktourist** [xuperchain/xuperunion#19]
dpos我知道，这个tdpos是什么，和dpos有什么区别呢

**Comment by xuperadmin** [comment]
一种DPOS算法，是我们自己实现的，我们做了很多优化和细节改造。
为了跟现有的DPOS算法做区分，我们加了一个t，t是时间的意思，当时我们希望引入原子钟做更好的优化。但是现在还没弄，已经能稳定work了，于是名字就这么保留了

**Comment by vktourist** [comment]
看了下咱们目前是35个节点吧，那目前的这些节点是怎么选出来的呢，有什么要求？stake是什么呢？另外如果我想成为节点该如何做呢？成为节点有什么收益吗？如果有收益，大概多少呢？

**Comment by xuperadmin** [comment]
开源讲的是代码代码，网络是用代码部署的实物。这里我们只谈代码，有下一步信息，敬请等待官方通知😄

**Comment by cszz12** [comment]
TDPOS有详细的文档描述吗？白皮书里没有看到

**Comment by cszz12** [comment]
好吧 还是有些文档吧 要不然用户也不放心

**Comment by xuperadmin** [comment]
恩，多谢建议，我们也在努力完善文档建设。资源挺紧张的，也希望更多的社区力量加入
