### ISSUE TITLE
xuperchain能跨链吗

### ISSUE THREAD

**Issue by vktourist** [xuperchain/xuperunion#20]
xuperchain能跨链吗？xuperchain上的各个平行链之间数据能相互访问交互吗？如果现有的eth、eos或者fabric要和xuperchain对接该如何对接呢？

**Comment by fxsjy** [comment]
超级链支持跨链，但此次开源的XuperUnion里面没有包含跨链的组件，XuperUnion 中的平行链不具备互操作性。
跨链的功能我们会后续开源在XuperCross这个项目里面。
