### ISSUE TITLE
Messages sent from unauthenticated nodes to authenticated  nodes should be refused.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#225]
**Brief of the issue**
Messages sent from unauthenticated nodes to authenticated  nodes should be refused.
But now,The messages sent from unauthenticated nodes to authenticated  nodes can be accepted.

**Your environment**
xchain-cli version V3.2

**Repo steps**
step1 
Turn off authentication switches for all nodes.
step2
Open the authentication switch for one of the nodes.
step3
Observing the heights of all nodes, it is found that the node with the switch on can receive messages.

**Expected behaviours**
Messages sent from unauthenticated nodes to authenticated  nodes should be refused.

**What actually happened**
Now,The messages sent from unauthenticated nodes to authenticated  nodes can be accepted.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
Closing this.
