### ISSUE TITLE
More forbidden causes the balance of address  to be unavailable

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#231]
**Brief of the issue**
More forbidden causes the balance of address  to be unavailable.

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
step1
Performing a transaction does not affect local utxo usage.
step2
More forbidden causes the balance of address  to be unavailable.And all forbidden were unsuccessful.
step3
Local utxo is unavailable.
![image](https://user-images.githubusercontent.com/51076943/61772921-f8a38600-ae25-11e9-86c1-490ebc197cc4.png)

**Expected behaviours**
Describe what  you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
Closing this.
