### ISSUE TITLE
Vm开源了没有，兼容性怎么样

### ISSUE THREAD

**Issue by hunjixin** [xuperchain/xuperunion#24]
简单的翻了下，没找到明确的执行器。有计划写个执行器么。

**Comment by Rcvisual** [comment]
它好像是通过WASM执行的，通过将C++和GO转换为WASM然后执行相应函数通过RPC调用对应服务：
路径在这：contractsdk/go/driver/wasm/context.go

**Comment by hunjixin** [comment]
@Rcvisual 

```
var resp code.Response
	methodName := ctx.Method()
	contractv := reflect.ValueOf(contract)
	methodv := contractv.MethodByName(strings.Title(methodName))
	if !methodv.IsValid() {
		resp = code.Errors("bad method " + methodName)
		returnResponse(&resp)
		return
	}
	method, ok := methodv.Interface().(func(code.Context) code.Response)
	if !ok {
		resp = code.Errors("bad method type " + methodName)
		returnResponse(&resp)
		return
	}
```
怎么说呢，貌似没有wasm执行器

**Comment by icexin** [comment]
wasm执行器代码在xvm目录，具体的业务逻辑处理在contract/wasm目录下

**Comment by duanbing** [comment]
可以看下XVM的实现。  基本过程是wasm -> code injection ->  c -> dylib.    然后go里面调用特定的几个导出函数符号执行。wasm import的符号会在c里面体现为外部导入符号，然后通过cgo，在go里面暴露出来。这个方式算是一种比较巧妙而且简洁的方式吧。
另外wavm也支持。 只是代码还没有上传。

**Comment by hunjixin** [comment]
@duanbing 这样玩。那跨平台怎么办，dll,so,dylib 都要么

**Comment by icexin** [comment]
动态库的生成是在运行链的节点上动态生成的，指令的统计注入在生成的c代码里面

**Comment by duanbing** [comment]
算力评估可以参考下https://github.com/duanbing/WAVM/blob/master/Gas.md 思路是类似的。

**Comment by hunjixin** [comment]
@duanbing 类似life的实现方式是吧，注入addgas指令

**Comment by hunjixin** [comment]
@duanbing 有开发社区，q群么，

**Comment by duanbing** [comment]
@hunjixin  注入的思路大概都是在BasicBlock里面进行统计。 这个要加估计都一样，包括ewasm。 有微信群。 readme下面有微信联系方式了。

**Comment by icexin** [comment]
有问题可以在微信群里面讨论，关闭了
