### ISSUE TITLE
Test consenus tdpos run_test.go plugin problem

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#248]
**Brief of the issue**
When I run  consensus/tdpos/run_test.go ，I have a problem about plugin
**Your environment**
Ubuntu 16.04  gcc 5.4.0 go 1.12.5
**Repo steps**
 When I tested it,
https://github.com/xuperchain/xuperunion/blob/04264af277c5d8feb124eb288960b2416ad9a8d9/consensus/tdpos/run_test.go#L124
**What actually happened**
I met
t=2019-07-29T00:40:24-0700 lvl=trce msg="Plugin conf load successfully!" module=pluginmgr pluginCount=6
t=2019-07-29T00:40:24-0700 lvl=warn msg="Warn: plugin open failed!" module=pluginmgr pluginname=kv err="plugin.Open(\"plugins/kv/kv-ldb-single.so.1.0.0\"): plugin was built with a different version of package math/bits"
t=2019-07-29T00:40:25-0700 lvl=trce msg="Plugin conf load successfully!" module=pluginmgr pluginCount=6
t=2019-07-29T00:40:25-0700 lvl=warn msg="Warn: plugin open failed!" module=pluginmgr pluginname=kv err="plugin.Open(\"plugins/kv/kv-ldb-single.so.1.0.0\"): plugin was built with a different version of package math/bits"
t=2019-07-29T00:42:32-0700 lvl=trce msg="Plugin conf load successfully!" module=pluginmgr pluginCount=6
t=2019-07-29T00:42:32-0700 lvl=trce msg="Load a plugin successfully" module=pluginmgr name=kv subtype=default
t=2019-07-29T00:42:32-0700 lvl=warn msg="Warn: plugin open failed!" module=pluginmgr pluginname=crypto err="plugin.Open(\"plugins/crypto/crypto-default.so.1.0.0\"): plugin was built with a different version of package github.com/xuperchain/xuperunion/pb"

Is it possible that I have two different copies of package，but I do not find it.

**Comment by yucaowang** [comment]
Thanks for the issue, did you changed the code and ran 'make test' without ran 'make' before?
Each time when you modify the code, please run 'make' before 'make test' to make sure all plugins using the latest common packages with the xchain main program.

**Comment by Rcvisual** [comment]
Thank you
