### ISSUE TITLE
Test Network Command parameter error

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#273]
**Brief of the issue**
Describe here
在超级链测试网络使用指南,4.2合约账户充入测试资源,
Step4: 将原始交易以及签名发送出去，命令如下： ./xchain-cli multisig send my.sign complianceCheck.out --tx ./rawTx.out -H 14.215.179.74:37101
**Your environment**
XuperUnion and OS/Go/gcc version etc.
Ubuntu16.04
**Repo steps**
Describe how to reproduce this issue.
不能正常执行
**Expected behaviours**
Describe what you expected to happen.
./xchain-cli multisig send my.sign complianceCheck.out,my.sign --tx ./rawTx.out -H 14.215.179.74:37101
**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.
 ./xchain-cli multisig send my.sign complianceCheck.out --tx ./rawTx.out -H 14.215.179.74:37101
**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by yucaowang** [comment]
Can you please show us the AuthRequire list, it's default in 'data/acl/addrs'.

**Comment by Rcvisual** [comment]
是的,我在3.3 设置合约账户ACL这边设置出错,直接按照模板设置ak1没有设置aksWeight为账户地址
{
    "module_name": "xkernel",
    "method_name": "SetAccountAcl",
    "args" : { 
        "account_name": "XC1234098776890654@xuper",
        "acl": "{\"pm\": {\"rule\": 1,\"acceptValue\": 1},\"aksWeight\": {\"ak1\": 1}}"
    }   
}
但是,你们,4.2合约账户充入测试资源,
Step4: 将原始交易以及签名发送出去，命令如下： ./xchain-cli multisig send my.sign complianceCheck.out --tx ./rawTx.out -H 14.215.179.74:37101
这个命令是错误的,应该为
./xchain-cli multisig send my.sign complianceCheck.out,my.sign --tx ./rawTx.out -H 14.215.179.74:37101
我是这么测试通过的,谢谢
