### ISSUE TITLE
链内并行在开源版本实现了吗？

### ISSUE THREAD

**Issue by gongliaoan** [xuperchain/xuperunion#29]
链内并行在开源版本实现了吗？翻了一遍代码好像没看到。

**Comment by fxsjy** [comment]
实现了，在func (xc *XChainCore) PostTx中。
https://github.com/xuperchain/xuperunion/blob/master/core/xchaincore.go#L659

节点收到一个tx后，除了校验密码学签名， 还会校验其依赖的Input哈希指针（指向依赖的其他tx output)是否有效（up to date)，如果有效则加载数据构造合约执行环境，然后重新执行合约，看输出的数据是否和tx中声明的写集合“TxOutputExts“一致。这整个过程都是无锁的，因此能并行，利用多核能力。

验证通过后，最后调用doTxInternal写入账本， 这个过程是有锁的，会再次check 哈希指针的有效性，因为前面放锁了。
简单而言，是一种乐观锁实现。

**Comment by HelloHG** [comment]
> 实现了，在func (xc *XChainCore) PostTx中。
> https://github.com/xuperchain/xuperunion/blob/master/core/xchaincore.go#L659
> 
> 节点收到一个tx后，除了校验密码学签名， 还会校验其依赖的Input哈希指针（指向依赖的其他tx output)是否有效（up to date)，如果有效则加载数据构造合约执行环境，然后重新执行合约，看输出的数据是否和tx中声明的写集合“TxOutputExts“一致。这整个过程都是无锁的，因此能并行，利用多核能力。
> 
> 验证通过后，最后调用doTxInternal写入账本， 这个过程是有锁的，会再次check 哈希指针的有效性，因为前面放锁了。
> 简单而言，是一种乐观锁实现。

您好，可回归侧链的部分在哪个部分？我并没有找到侧链部分的代码，谢谢。
