### ISSUE TITLE
Split utxo need preExec operation.

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#294]
**Brief of the issue**
Describe here
![image](https://user-images.githubusercontent.com/51076943/63072278-840bc500-bf55-11e9-83ea-bd43a0b69bc9.png)
![image](https://user-images.githubusercontent.com/51076943/63072309-b1587300-bf55-11e9-957c-d659ba1d3e8f.png)

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by ToWorld** [comment]
Closing this
