### ISSUE TITLE
Support Multisignature in default/schnorr crypto client

### ISSUE THREAD

**Issue by yucaowang** [xuperchain/xuperunion#305]
## Brief of your idea
Support Multisignature in default/schnorr crypto client, so that client could generate real multi signature which contains only one signature for several private keys.

For Multisignature please referring to [wikipedia](https://en.wikipedia.org/wiki/Multisignature)

## What could be better if XuperChain using your idea
Using multisig could improve the performance of validating a group of user's signatures. Without multisign, we need validate N signatures for a group of N users, but with multisig, we only need to verify one signature

## Are there any side effects?
More complicated for cli to preparing multisig

**Comment by ToWorld** [comment]
Closing this.
