### ISSUE TITLE
Cannot access xuperunion rpc interface by http post method.

### ISSUE THREAD

**Issue by foreso-GitHub** [xuperchain/xuperunion#312]
**Brief of the issue**
Hi there, I am trying the xuperchain.
I run an xuperchain, single node in ubuntu.  I can get chain info like balance, block by xchain-cli console as following.
./xchain-cli block a64926ebe7bf97f28fddf1aacd4d3338e1d84a44f69ccbb8ae962228b12ba399 -H 192.168.0.23:37101
It works.

But I cannot access rpc interface by http post method.
For example:
curl -X POST http://127.0.0.1:37101/v1/get_block -d BlockID=a64926ebe7bf97f28fddf1aacd4d3338e1d84a44f69ccbb8ae962228b12ba399
The result is:
curl: (56) Recv failure: Connection reset by peer

Is there anything I should pay attention to?

Thanks!

**Your environment**
XuperUnion: 
OS: ubuntu 16.04
Go: go version go1.12.9 linux/amd64

**Repo steps**
curl -X POST http://127.0.0.1:37101/v1/get_block -d BlockID=a64926ebe7bf97f28fddf1aacd4d3338e1d84a44f69ccbb8ae962228b12ba399

**Expected behaviours**
The block info.

**What actually happened**
curl: (56) Recv failure: Connection reset by peer

**Additional information**

**Comment by foreso-GitHub** [comment]
I used this command to start xuperunion.
nohup ./xchain &

is there any parameter needs to open the rpc function in this command?

**Comment by yucaowang** [comment]
I'm sorry but the xchain service only support GRPC now. If you want to communicate with xchain via HTTP, you need to use a HTTP adapter which we are not open-sourced by now.

**Comment by foreso-GitHub** [comment]
Thanks @yucaowang!

So no websocket either, right?

If possible, could you please give me a sample or codes that communicate with xchain via GRPC?

**Comment by yucaowang** [comment]
@foreso-GitHub 
Yes, websocket is also absence at the moment.

For GRPC sample, please referring to our "cmd/cli" package, the command tool is communicating with xchain node using GRPC.

**Comment by ToWorld** [comment]
Closing this.
