### ISSUE TITLE
wiki  cmd error: ./bin/xchain transfer 

### ISSUE THREAD

**Issue by cuishaoshao** [xuperchain/xuperunion#386]
**Brief of the issue**
Describe here
wiki
cmd error
3.5.5 撤销提名 && 撤销投票
./bin/xchain transfer --to Y4TmpfV4pvhYT5W17J7TqHSLo6cqq23x3 --desc=./revoke_demo.json --amou

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by yucaowang** [comment]
Hi @cuishaoshao, we cannot get any useful information from the description you provided, can you please provide more info about "revoke_demo.json" and the detailed error message.

**Comment by cuishaoshao** [comment]
@yucaowang 
I mean  document describe cmd   "./bin/xchain transfer"  error,i think cmd  is "./xchain-cli transfer"

**Comment by yucaowang** [comment]
> @yucaowang
> I mean document describe cmd "./bin/xchain transfer" error,I think cmd is "./xchain-cli transfer"

Oh... Yes, the command is wrong, we've correct this command in our wiki.
Thanks @cuishaoshao !
