### ISSUE TITLE
无力make诶

### ISSUE THREAD

**Issue by cr4fun** [xuperchain/xuperunion#51]
go版本
1.12.5
gcc版本 7.4.0

错误如下
![1559616987921](https://user-images.githubusercontent.com/38368200/58848020-8f37a000-864a-11e9-8040-431102fe0011.jpg)

**Comment by icexin** [comment]
打印一下`go env`的输出

**Comment by fxsjy** [comment]
@cr4fun , 请给出go env的输出便于排查问题，否则这个issue就先关闭了。
