### ISSUE TITLE
数据服务设计是两层设计吗？

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#52]
是一层基于leveldb的数据表封装，还有一层是LRU缓冲？直接读取数据库表文件效率怎么样？还是维护了一个最新的UTXO表，不是账户状态机对应的最新账户库？是基于什么考虑的，选择了UTXO模型？

**Comment by ToWorld** [comment]
1. 是一层基于leveldb的数据表封装，还有一层是LRU缓冲？
针对UTXO，第一层是KV存储，第二层是一个内存级别的Cache。Cache的具体实现参考xuperchain/xuperunion/utxo_cache.go。
2. 直接读取数据库表文件效率怎么样？
直接读取底层KV数据肯定比从内存读更慢。
3.还是维护了一个最新的UTXO表，不是账户状态机对应的最新账户库？
UTXO只有一张表，可以参考UTXO中每一条记录的数据结构，具体代码参考：xuperchain/xuperunion/utxo_item.go xuperchain/xuperunion/utxo.go

**Comment by Rcvisual** [comment]
> 1. 是一层基于leveldb的数据表封装，还有一层是LRU缓冲？
>    针对UTXO，第一层是KV存储，第二层是一个内存级别的Cache。Cache的具体实现参考xuperchain/xuperunion/utxo_cache.go。
> 2. 直接读取数据库表文件效率怎么样？
>    直接读取底层KV数据肯定比从内存读更慢。
> 3. 还是维护了一个最新的UTXO表，不是账户状态机对应的最新账户库？
>    UTXO只有一张表，可以参考UTXO中每一条记录的数据结构，具体代码参考：xuperchain/xuperunion/utxo_item.go xuperchain/xuperunion/utxo.go

其他数据就是直接访问底层kv数据库吧？没有任何cache设计，是吧

**Comment by ToWorld** [comment]
No. Other data also uses the cache.

Closing this.
