### ISSUE TITLE
部署合约,收集多重签名发送签名时好像发现了一个bug

### ISSUE THREAD

**Issue by gaojunjie03** [xuperchain/xuperunion#541]
我的合约账号acl配置如下:
{
  "pm": {
    "rule": 1,
    "acceptValue": 0.6
  },
  "aksWeight": {
    "maoJ17a3SZPdXMSEB5F4pn1PELKdj2SAq": 0.6
  }
}

我的其中一个节点的data/acl/address是:
XC1572318884355000@xuper/maoJ17a3SZPdXMSEB5F4pn1PELKdj2SAq

maoJ17a3SZPdXMSEB5F4pn1PELKdj2SAq这个地址对应的节点是192.168.4.132。当我在192.168.4.138节点发起部署合约的时候，首先对本地138进行签名得到138.sign，然后我应该是对132进行签名，然而我选择了对192.168.4.133另外一个节点进行签名得到133.sign, 最终我发送签名
./xchain-cli multisig send --tx tx.out 138.sign 133.sign 居然成功了  这是一个bug吗？

**Comment by yucaowang** [comment]
Hi @gaojunjie03 , 您能提供更多信息吗？比如./xchain-cli multisig gen 命令生成的tx.out数据，是可以通过./xchain-cli multisig check 来查看内容的，我们可以看下里面打包的initiator和auth_require是什么。

**Comment by gaojunjie03** [comment]
"initiator": "Z5h8ABqbv6uEE4gpJaBLHCpSvMMGeh2td",
  "authRequire": [
    "XC1572318884355000@xuper/maoJ17a3SZPdXMSEB5F4pn1PELKdj2SAq"
  ],
Z5h8ABqbv6uEE4gpJaBLHCpSvMMGeh2td 是192.168.4.138

**Comment by gaojunjie03** [comment]
> Hi @gaojunjie03 , 您能提供更多信息吗？比如./xchain-cli multisig gen 命令生成的tx.out数据，是可以通过./xchain-cli multisig check 来查看内容的，我们可以看下里面打包的initiator和auth_require是什么。

"initiator": "Z5h8ABqbv6uEE4gpJaBLHCpSvMMGeh2td",
"authRequire": [
"XC1572318884355000@xuper/maoJ17a3SZPdXMSEB5F4pn1PELKdj2SAq"
],


Z5h8ABqbv6uEE4gpJaBLHCpSvMMGeh2td 是192.168.4.138

**Comment by yucaowang** [comment]
@gaojunjie03 ，可以把整个交易贴出来我分析下。

**Comment by gaojunjie03** [comment]
> @gaojunjie03 ，可以把整个交易贴出来我分析下。

这个是部署合约的时候出现的。。这个tx.out 非常大。。。不好发，我再多测试几遍
