### ISSUE TITLE
关于数值单位和单位转换功能的建议

### ISSUE THREAD

**Issue by oblivioned** [xuperchain/xuperunion#596]
**Brief of your idea**
关于数值单位和单位转换的建议

因为大数的表现问题，BigInt类型并不能支持小数表示，为了更好区分数值，同时也可以让用户，开发者不用长时间面对超长的数值，如核算手续费等，建议为每10 ** 3 增加一个单位。

比如余额为:
1 = 1 (XB)
1,000 = 1 (KXB)
1000,000 = 1 (GXB)
100,000,000 = 1 (TXB)

(备注：单位只是举例说明）

同时增加转换如：

函数原型：

> Units.toXB( blanace, balnaceUnit )
> Units.fromXB( blanace, balnaceUnit )
```
Units.toXB( 1, Units.TXB )
100,000,000 (XB)

Units.toXB( 1, Units.GXB )
100,000 (XB)

Units.fromXB(123456789, Units.TXB)
1.234,567,89 (TXB)

Units.fromXB(123456789, Units.GXB)
1,234.567,89 (GXB)
```

然后在所有平台的SDK中作出对应平台的实现，通讯之间使用的单位一律为 XB，即最小单位。

**Comment by qizheng09** [comment]
Thanks  for your advice, we have been add this to our feature list and will consider whether and when to support this issue.

**Comment by qizheng09** [comment]
Welcome to follow-up questions, here closed first.
