### ISSUE TITLE
关于增加交易记录查询功能的建议

### ISSUE THREAD

**Issue by oblivioned** [xuperchain/xuperunion#597]
**Brief of your idea**
关于增加交易记录查询功能的建议

查询对应地址的交易记录
```
./xchain-cli tx query --from [Address or Account] --pageindex 0 --pagesize 20 --desc --detail
--from : 查询的地址或者合约账户
--pageindex: 页码
--pagesize: 每页大小
--desc：倒序，不填表示升序
--detail：返回交易的详细信息，否则仅返回交易的Hash和基础信息
```

如果不追加--detail参数则可以返回交易中的几个关键参数如
1.Hash值
2.交易所在块号和块Hash
3.initor
4.to
5.amount
6.fee
7....

**Comment by qizheng09** [comment]
Thanks  for your advice, we have been add this to our feature list and will consider whether and when to support this issue.

**Comment by qizheng09** [comment]
Welcome to follow-up questions, here closed first.
