### ISSUE TITLE
节点启动失败

### ISSUE THREAD

**Issue by YangArtWish** [xuperchain/xuperunion#598]
**Brief of the issue**
Describe here

不同机器上，三台虚拟机，每一台虚拟机一个节点，node1节点启动成功, 而node2和node3节点启动失败，自动断开
![微信图片_20200104130058](https://user-images.githubusercontent.com/52487140/71760069-85cd2980-2ef2-11ea-9624-152358210a0e.png)
![微信图片_20200104130105](https://user-images.githubusercontent.com/52487140/71760070-8665c000-2ef2-11ea-8661-6547bd94a040.png)

**Your environment**
XuperUnion and OS/Go/gcc version etc.

XuperUnion版本是3.3版本，环境采用const7是虚拟机形式， go版本是13.1.1版本，
gcc是gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

**Repo steps**
Describe how to reproduce this issue.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.
![微信图片_20200104130058](https://user-images.githubusercontent.com/52487140/71760073-91205500-2ef2-11ea-8dd2-30ccec5224a1.png)
![微信图片_20200104130105](https://user-images.githubusercontent.com/52487140/71760074-91b8eb80-2ef2-11ea-8e46-d9ee8e62d346.png)
白色背景为node1节点
黑色背景为node2节点

**Comment by qizheng09** [comment]
Thanks for your issue. This has been fixed by wechat and will closed there.
