### ISSUE TITLE
智能合约希望可以提供一个溯源的api

### ISSUE THREAD

**Issue by gaojunjie03** [xuperchain/xuperunion#600]
**Brief of your idea**
目前溯源，我知道的 只能根据交易id来进行溯源，这样感觉不友好，希望可以通过编写智能合约根据key来溯源历史版本数据(并且可以限制条数)

**What could be better if XuperChain using your idea**
客户端不需要关心区块链交易详情包括记录交易id，我只需知道我的key就可以知道这个key的历史版本

**Comment by qizheng09** [comment]
Thanks  for your advice, we have been add this to our feature list and will consider whether and when to support this issue.

**Comment by qizheng09** [comment]
Welcome to follow-up questions, here closed first.
