### ISSUE TITLE
怎么设置合约方法的调用权限？

### ISSUE THREAD

**Issue by qmarliu** [xuperchain/xuperunion#602]
我布置ERC20合约后。

我发现任何人发起交易都能转走合约里面的币。

我如果希望XC1111111111111111@xuper里面的币只能由XC1111111111111111@xuper签名后才能转，有没有机制可以做到？

**Comment by qizheng09** [comment]
You can use https://github.com/xuperchain/xuperunion/tree/master/contractsdk/cpp/XRC/xrc0  issue #421. The  more document will be released soon.

**Comment by qizheng09** [comment]
Welcome to follow-up questions, here closed first.
