### ISSUE TITLE
Add ip limit

### ISSUE THREAD

**Issue by ToWorld** [xuperchain/xuperunion#64]
**Brief of the issue**
Add the function to limit the amount of same ip, including server and client limitation.

**Your environment**
XuperUnion and OS/Go/gcc version etc.
OS: Linux
Go: 1.12.5
gcc:  g++ (GCC) 4.8.2

**Expected behaviours**
Describe what you expected to happen.
Limiting the amount of same ip when a new stream generated, default the limitation of same ip is 10, and you can adjust the parameter in the config file.

**Comment by yucaowang** [comment]
Close this issue as fixed #71
