### ISSUE TITLE
libp2p in go.mod is too old

### ISSUE THREAD

**Issue by pefish** [xuperchain/xuperunion#74]
libp2p in go.mod is too old. Can you upgrade them?

**Comment by qizheng09** [comment]
Thank you for your proposal  and we will update it in the near future.

**Comment by xiaods** [comment]
add two coins:

in p2pv2 module, i found the the import lib  
`crypto "github.com/libp2p/go-libp2p-crypto" `  now is deprecated.
does pr is welcome? if sure, i can pr and upgrade it.

**Comment by ToWorld** [comment]
Thank you very much. Please don't hesitate to submit a pr.
