### ISSUE TITLE
Automatic rollback of transactions that have not been confirmed for too long

### ISSUE THREAD

**Issue by fxsjy** [xuperchain/xuperunion#80]
**Brief of the issue**
In some cases, local node may have transactions that have been unsuccessfully confirmed, such as read/write set conflicts, and so on.Therefore, there needs to be a mechanism to clean up local unconfirmed transactions that have not been successfully confirmed for a long time.The default value is 300 seconds, which can be configured in the file of xchain.yaml.

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
make a network of tow nodes, one is miner, the other is verify node.
Then, shutdown the miner, and submit a transaction to verify node.
Wait 300 seconds, and then restart the miner.

**Expected behaviours**
The previous submitted transaction should be rollback, and we can see some undo logs in xchain.log.

**Comment by yucaowang** [comment]
Close this issue as fixed #82
