### ISSUE TITLE
Config problem in common/config/config.go 

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#87]
**Brief of the issue**
Describe here
有一个配置问题和注释拼写错误
**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
Describe how to reproduce this issue.
common/config/config.go 285
common/config/config.go 195
**Expected behaviours**
Describe what you expected to happen.
func newP2pConfigWithDefault() P2PConfig {
	return P2PConfig{
		...
		IsNat:            DefaultNetIsNat,
		IsSecure:      DefaultNetIsSecure,
		...
	}
}

// KernelConfig kernel config
**What actually happened**
Describe what actually happened. Include the full traceback if there was an exception.
func newP2pConfigWithDefault() P2PConfig {
	return P2PConfig{
		...
		IsNat:            DefaultNetIsNat,
		IsSecure:         DefaultNetIsNat,
		...
	}
}

// KernelConfig kerner config

**Comment by MichelleZ** [comment]
We sincerely invite you to submit this change. You may submit a PR to modify it, will you?

**Comment by Rcvisual** [comment]
> We sincerely invite you to submit this change. You may submit a PR to modify it, will you?

ok

**Comment by yucaowang** [comment]
Close it as fixed: #93
