### ISSUE TITLE
百度区块链白皮书首页第一句话就是错的！请留意，正确的说法请看这

### ISSUE THREAD

**Issue by 1024-man** [xuperchain/xuperunion#88]
先有区块链?先有比特币？两者发展局限性分析
https://mp.weixin.qq.com/s/zSQ1f9pieRh-SUqpxuKxpA
摘抄来源--微信公众号：财貌直升机

**Comment by 1024-man** [comment]
白皮书原文“区块链起源于比特币”——这一表述是事实错误。。。

**Comment by fxsjy** [comment]
Please submit issue according to our issue template. And, we suggest using English at Github.

**Comment by fxsjy** [comment]
Close this.

**Comment by 1024-man** [comment]
what?  a can't use english! you are chinese ?  baidu is chinese company! we can no zhuangbi?
